#!/bin/bash

FILES=()
DATE=$(date +%Y-%m-%d-%H-%M-%S)
TMPDIR=/tmp/$(whoami)/tqsafemerge/$DATE
OUTPUT="samples_merged.root"

while [[ $# -gt 1 ]]; do
    key="$1"
    
    case $key in
	--options)
	    shift
	    OPTIONS="$@"
	    break
	    ;;
	-o|--output)
	    OUTPUT="$2"
	    shift
	    ;;
	-n)
	    CHUNKS="$2"
	    shift 
	    ;;
	--tmp)
	    TMPDIR="$2"
	    shift 
	    ;;
	*)
	    if [ -f $1 ]; then
		FILES+=($1)
	    else
		echo "unknown option: $1"
		exit
	    fi
	    ;;
    esac
    shift # past argument or value
done


while [ ${#FILES[@]} -gt 1 ]; do
    TMPOUT=$TMPDIR/tmp.${#FILES[@]}.root
    part=( "${FILES[@]:0:CHUNKS}" )
    $TQPATH/share/tqmerge ${OPTIONS} -o $TMPOUT ${part[*]} 
    FILES=("${FILES[@]:CHUNKS}" $TMPOUT) 
done

mv ${FILES[0]} $OUTPUT
