name: Checks test

on:
  issue_comment:
    types: [created]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.issue.number }}-${{ github.event.comment.user.login }}-${{ contains(github.event.comment.body, '/run standalone') }}-${{ contains(github.event.comment.body, '/run cmssw') }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  standalone:
    if: >
      github.event.issue.pull_request &&
      contains(github.event.comment.body, '/run check') &&
      github.event.comment.user.login == 'ariostas'
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          ref: refs/pull/${{ github.event.issue.number }}/head
      - name: Get commit SHA
        run: |  
          sha=$(git rev-parse HEAD)
          echo "COMMIT_SHA=$sha" >> $GITHUB_ENV
      - uses: LouisBrunner/checks-action@v1.6.1
        if: always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          sha: ${{ env.COMMIT_SHA }}
          name: Test check
          conclusion: ${{ job.status }}
